[rust]
edition = "2021" #在线运行用2021版本的

[book]
authors = ["MoXiang"]
language = "zh=CN"
multilingual = false
src = "src"
title = "Android知识总结(Android Course)"

[output.html]
additional-css = ["theme/style.css"]
# additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/yuchuangu85/Android-Course"
edit-url-template = "https://github.com/yuchuangu85/Android-Course/edit/main/{path}"

[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = true
level = 0
